hl.window_rule({ name = "float-pavucontrol", match = { class = "^org\\.pulseaudio\\.pavucontrol$" }, float = true })
hl.window_rule({ name = "float-pip-generic", match = { title = "^Picture in picture$" }, float = true })
hl.window_rule({ name = "float-save-dialog", match = { title = "^Save File$" }, float = true })
hl.window_rule({ name = "float-open-dialog", match = { title = "^Open File$" }, float = true })
hl.window_rule({ name = "float-libre-pip", match = { class = "^LibreWolf$", title = "^Picture-in-Picture$" }, float = true })
hl.window_rule({ name = "float-blueman", match = { class = "^blueman-manager$" }, float = true })
hl.window_rule({ name = "float-xdg-portal", match = { class = "^xdg-desktop-portal-(gtk|kde|hyprland)$" }, float = true })
hl.window_rule({ name = "float-polkit", match = { class = "^(polkit-gnome-authentication-agent-1|hyprpolkitagent|org\\.kde\\.polkit-kde-authentication-agent-1)$" }, float = true })
hl.window_rule({ name = "float-cachyos-hello", match = { class = "^CachyOSHello$" }, float = true })
hl.window_rule({ name = "float-zenity", match = { class = "^zenity$" }, float = true })
hl.window_rule({ name = "float-steam-updater", match = { title = "^Steam - Self Updater$" }, float = true })
hl.window_rule({ name = "float-kitty-float", match = { class = "^kitty-float$" }, float = true, size = "900 600" })
hl.window_rule({ name = "pip-general", match = { title = "^Picture-in-Picture$" }, float = true, size = "960 540", move = "25% 25%" })
hl.window_rule({ name = "rounded-danmu-term", match = { title = "^(danmufloat|termfloat)$" }, rounding = 5 })
hl.window_rule({ name = "slide-in-terminals", match = { class = "^(kitty|Alacritty)$" }, animation = "slide right" })

hl.layer_rule({ name = "logout_dialog_anim", match = { namespace = "^logout_dialog$" }, animation = "slide top" })
hl.layer_rule({ name = "waybar_anim", match = { namespace = "^waybar$" }, animation = "slide down" })
hl.layer_rule({ name = "wallpaper_anim", match = { namespace = "^wallpaper$" }, animation = "fade 50%" })
